CC 	=	gcc
CFLAGS 	=
OBJ 	= 	$(patsubst %.c,%.o,$(wildcard *.c)) 
INCLUDE	=	

all: archive

archive: $(OBJ)
	ar rcs libdtp_posix.a *.o;

%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDE) -c $<



.PHONY clean, realclean:

clean:
	rm *.o
	

realclean: clean
	rm libdtp_posx.a

